//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeSpot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_booking
    {
        public int bk_id { get; set; }
        public string username { get; set; }
        public string vehicle_no { get; set; }
        public string vehicle_type { get; set; }
        public string slot { get; set; }
        public string color { get; set; }
        public System.DateTime ctime { get; set; }
        public System.DateTime duration { get; set; }
    }
}
