//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeSpot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_findspace
    {
        public int fs_id { get; set; }
        public System.DateTime arrival_time { get; set; }
        public string vehicle_type { get; set; }
        public string color { get; set; }
        public string geolocation { get; set; }
        public string parkslot { get; set; }
    }
}
