//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeSpot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_freeslot
    {
        public int freeslot_id { get; set; }
        public string agentinfree_name { get; set; }
        public string sllotinfree_name { get; set; }
        public string address { get; set; }
        public string Lat_infree { get; set; }
        public string Long_infree { get; set; }
        public int car_freeslot { get; set; }
        public int bike_freeslot { get; set; }
    }
}
