//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeSpot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_payment
    {
        public int id { get; set; }
        public long card_no { get; set; }
        public string exp_date { get; set; }
        public string cvv_code { get; set; }
        public string owner { get; set; }
    }
}
