//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeSpot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_agent
    {
        public int agent_id { get; set; }
        public string agent_name { get; set; }
        public string gmail { get; set; }
        public string phone_no { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}
